# Generated by Django 5.0.6 on 2024-07-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NTUT_Post',
            new_name='NTUT_Posts',
        ),
    ]
