# Generated by Django 5.0.6 on 2024-07-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0002_rename_ntut_post_ntut_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='ntut_posts',
            options={'verbose_name': 'NTUT Post', 'verbose_name_plural': 'NTUT Posts'},
        ),
        migrations.AlterModelOptions(
            name='stocks',
            options={'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
    ]
