# Generated by Django 5.0.6 on 2024-07-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0003_alter_news_options_alter_ntut_posts_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
