# Generated by Django 5.0.6 on 2024-07-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0005_alter_news_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='change_percent',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
