# Generated by Django 5.0.6 on 2024-07-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0006_alter_stocks_change_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
