# Generated by Django 5.0.6 on 2024-07-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0007_alter_stocks_change_alter_stocks_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
