# Generated by Django 5.0.6 on 2024-07-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0008_news_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='fetch_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
