# Generated by Django 5.0.6 on 2024-07-01 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='Delete_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_deleted'),
        ),
    ]
