# Generated by Django 5.0.6 on 2024-07-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_context_delete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='Delete_date',
            field=models.DateTimeField(null=True, verbose_name='date_deleted'),
        ),
    ]
